# Generated by Django 3.2.7 on 2021-12-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_logperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logborrow',
            name='borrowps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.logperson'),
        ),
        migrations.AddField(
            model_name='logborrow',
            name='borrowsl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.logitems'),
        ),
        migrations.AddField(
            model_name='logitems',
            name='itemtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.logtype'),
        ),
    ]
