# Generated by Django 3.2.7 on 2021-12-21 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_alter_logborrow_borrowdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logborrow',
            name='borrowdt',
            field=models.DateField(default=datetime.date.today, verbose_name='借出時間'),
        ),
    ]
